[book]
authors = []
language = "zh"
description = "robonix 手册"
src = "src"
title = "robonix 手册"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/syswonder/robonix"
mathjax-support = true
